version: 2.1

orbs:
  win-perf-diag: circle-makotom-orbs/windows-performance-diagnosis@volatile

jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.large
    steps:
      - checkout

      # Start recording
      - win-perf-diag/start-perflog
      - win-perf-diag/record-wpr-in-background:
          for-sec: 100
          split-by-sec: 30

      # This is the part to be diagnosed
      - run:
          name: Do something for 120 seconds
          shell: powershell.exe
          command: |
            $ErrorActionPreference = "Stop"

            Write-Host "Starting..."

            $procs = @()
            foreach ($iter in 0..4) {
                $procs += Start-Process -PassThru ./FlipFlop.exe 3072
            }

            Start-Sleep 120

            foreach ($proc in $procs) {
                Stop-Process $proc
            }

            Write-Host "DONE."

      # Stop recording and save records
      - win-perf-diag/ensure-and-save-wpr
      - win-perf-diag/stop-and-save-perflog
